import { DollarSign, LayoutDashboard, User2, Users } from "lucide-react";

export const items = [
  {
    title: "Dashboard",
    url: "/dashboard",
    icon: LayoutDashboard,
  },
  {
    title: "Users",
    url: "/users",
    icon: Users,
  },
  {
    title: "Payment Plans",
    url: "/plans",
    icon: DollarSign,
  },
];

export const baseStats = [
  {
    id: 1,
    icon: User2,
    value: "332",
    name: "Total Users",
    iconBg: "bg-orange-600/20",
    iconColor: "text-orange-600",
    trend: "+20.1% more than last month.",
  },
  {
    id: 2,
    icon: DollarSign,
    value: "$45,231.89",
    name: "Total Earnings",
    iconBg: "bg-green-600/20",
    iconColor: "text-green-600",
    trend: "-16.2% less than last month.",
  },
  {
    id: 3,
    icon: Users,
    value: "114",
    name: "Free vs Paid Users",
    iconBg: "bg-blue-600/20",
    iconColor: "text-blue-600",
    trend: "+23.7% more paid users than last month.",
  },
];

export const plans = [
  {
    id: 1,
    name: "Free",
    price: 0,
    users: 441,
    trend: "+20.1% more than last month.",
    bgColor: "chart-1",
  },
  {
    id: 2,
    name: "Basic",
    price: 20,
    users: 343,
    trend: "+20.1% more than last month.",
    bgColor: "chart-2",
  },
  {
    id: 3,
    name: "Pro",
    price: 50,
    users: 268,
    trend: "-20.1% less than last month.",
    bgColor: "chart-3",
  },
  {
    id: 4,
    name: "Premium",
    price: 100,
    users: 192,
    trend: "-20.1% less than last month.",
    bgColor: "chart-4",
  },
];

export const users = [
  {
    id: 1,
    plan: "free",
    email: "user1@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/1.jpg",
    isActive: true,
  },
  {
    id: 2,
    plan: "basic",
    email: "user2@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/2.jpg",
    isActive: false,
  },
  {
    id: 3,
    plan: "premium",
    email: "user3@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/3.jpg",
    isActive: true,
  },
  {
    id: 4,
    plan: "free",
    email: "user4@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/4.jpg",
    isActive: false,
  },
  {
    id: 5,
    plan: "basic",
    email: "user5@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/5.jpg",
    isActive: true,
  },
  {
    id: 6,
    plan: "premium",
    email: "user6@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/6.jpg",
    isActive: false,
  },
  {
    id: 7,
    plan: "free",
    email: "user7@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/7.jpg",
    isActive: true,
  },
  {
    id: 8,
    plan: "basic",
    email: "user8@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/8.jpg",
    isActive: false,
  },
  {
    id: 9,
    plan: "premium",
    email: "user9@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/9.jpg",
    isActive: true,
  },
  {
    id: 10,
    plan: "free",
    email: "user10@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/10.jpg",
    isActive: false,
  },
  {
    id: 11,
    plan: "basic",
    email: "user11@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/11.jpg",
    isActive: true,
  },
  {
    id: 12,
    plan: "premium",
    email: "user12@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/12.jpg",
    isActive: false,
  },
  {
    id: 13,
    plan: "free",
    email: "user13@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/13.jpg",
    isActive: true,
  },
  {
    id: 14,
    plan: "basic",
    email: "user14@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/14.jpg",
    isActive: false,
  },
  {
    id: 15,
    plan: "premium",
    email: "user15@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/15.jpg",
    isActive: true,
  },
  {
    id: 16,
    plan: "free",
    email: "user16@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/16.jpg",
    isActive: false,
  },
  {
    id: 17,
    plan: "basic",
    email: "user17@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/17.jpg",
    isActive: true,
  },
  {
    id: 18,
    plan: "premium",
    email: "user18@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/18.jpg",
    isActive: false,
  },
  {
    id: 19,
    plan: "free",
    email: "user19@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/19.jpg",
    isActive: true,
  },
  {
    id: 20,
    plan: "basic",
    email: "user20@example.com",
    image: "https://randomuser.me/api/portraits/thumb/men/20.jpg",
    isActive: false,
  },
];
